config/routes.rb
HijriCalendar::Application.routes.draw do
  resource :calendar, only: [:show], controller: :calendar
  root to: "calendar#show"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end
end

app/views/calendar/show.html.haml
.row
  .col-md-12.text-center
    .well.controls
      = link_to calendar_path(date: @date - 1.month), class: "btn btn-default pull-left" do
        %i.fa.fa-angle-double-left.fa-2x
      = link_to calendar_path(date: @date + 1.month), class: "btn btn-default pull-right" do
        %i.fa.fa-angle-double-right.fa-2x
      %h2= Hijri.convert(@date).month_name

      %p.pull-left
        Hijri #{Hijri.convert(@date).year}
      %p.pull-right
        = "#{@date.strftime("%B")} #{@date.year}"
      %br  
.row
  .col-md-12
    = calendar @date do |date|
      = date.strftime("%B")
      = date.day
      %br/
      %span.hijri-day
        = Hijri.convert(date.to_time).day

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title -: Hijri Calendar :-
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      / Static navbar
      .navbar.navbar-default{:role => "navigation"}
        .container-fluid
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "#"} Hijri Calendar
          .navbar-collapse.collapse
            %ul.nav.navbar-nav.navbar-right
              %li
                %a{:href => "#"} About
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Subscribe
                  %span.caret
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:href => "#"} Action
                  %li
                    %a{:href => "#"} Another action
                  %li
                    %a{:href => "#"} Something else here
                  %li.divider
                  %li.dropdown-header Nav header
                  %li
                    %a{:href => "#"} Separated link
                  %li
                    %a{:href => "#"} One more separated link                
          / /.nav-collapse
        / /.container-fluid    

      = yield